//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::B11: return "Idle 1 (B11)";
		case Gpio::B9: return "Fuel Pump (B9)";
		case Gpio::C13: return "Tach (C13)";
		case Gpio::C6: return "Hall 2 (C6)";
		case Gpio::C7: return "VSS 2 VR (C7)";
		case Gpio::D10: return "Ignition 3 (D10)";
		case Gpio::D11: return "Ignition 4 (D11)";
		case Gpio::D3: return "VVT 1 (D3)";
		case Gpio::D4: return "VVT 2 (D4)";
		case Gpio::D5: return "USART-TX (D5)";
		case Gpio::D6: return "USART-RX (D6)";
		case Gpio::D7: return "Spare 2 (D7)";
		case Gpio::D8: return "Ignition 1 (D8)";
		case Gpio::D9: return "Ignition 2 (D9)";
		case Gpio::E0: return "Crank VR (E0)";
		case Gpio::E1: return "Cam VR (E1)";
		case Gpio::E10: return "Injector 4 (E10)";
		case Gpio::E11: return "Injector 5 (E11)";
		case Gpio::E12: return "Injector 6 (E12)";
		case Gpio::E13: return "Injector 7 (E13)";
		case Gpio::E14: return "Injector 8 (D13)";
		case Gpio::E15: return "VSS 1 VR (E15)";
		case Gpio::E2: return "Spare 3 (E2)";
		case Gpio::E3: return "Idle 2 (E3)";
		case Gpio::E5: return "Spare 1 (E5)";
		case Gpio::E6: return "Fan (E6)";
		case Gpio::E7: return "Injector 1 (E7)";
		case Gpio::E8: return "Injector 2 (E8)";
		case Gpio::E9: return "Injector 3 (E9)";
		case Gpio::F0: return "Ignition 5 (F0)";
		case Gpio::F1: return "Ignition 6 (F1)";
		case Gpio::F10: return "Boost (F10)";
		case Gpio::F2: return "Ignition 7 (F2)";
		case Gpio::F3: return "Ignition 8 (F3)";
		case Gpio::G10: return "High 2 (G10)";
		case Gpio::G11: return "High 3 (G11)";
		case Gpio::G12: return "High 4 (G12)";
		case Gpio::G13: return "ETB_DIS/StepDir (G13)";
		case Gpio::G14: return "ETB PWM (G14)";
		case Gpio::G15: return "ETB_DIR/StepStep (G15)";
		case Gpio::G2: return "Launch (G2)";
		case Gpio::G3: return "Flexfuel (G3)";
		case Gpio::G4: return "Digital 1 (G4)";
		case Gpio::G5: return "Digital 2 (G5)";
		case Gpio::G6: return "Digital 3 (G6)";
		case Gpio::G7: return "Digital 4 (G7)";
		case Gpio::G8: return "Hall 1 (G8)";
		case Gpio::G9: return "High 1 (G9)";
		default: return nullptr;
	}
	return nullptr;
}
